//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ortho.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ortho.Shared.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Simulation Inputs.
        /// </summary>
        public static string Additional_Simulation_Inputs {
            get {
                return ResourceManager.GetString("Additional Simulation Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Time Adjustments.
        /// </summary>
        public static string Arrival_Time_Adjustments {
            get {
                return ResourceManager.GetString("Arrival Time Adjustments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assay Mapping.
        /// </summary>
        public static string Assay_Mapping {
            get {
                return ResourceManager.GetString("Assay Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Details.
        /// </summary>
        public static string Customer_Details {
            get {
                return ResourceManager.GetString("Customer Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Inputs.
        /// </summary>
        public static string Demand_Inputs {
            get {
                return ResourceManager.GetString("Demand Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Summary and Growth.
        /// </summary>
        public static string Demand_Summary_and_Growth {
            get {
                return ResourceManager.GetString("Demand Summary and Growth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIS File Selection and Column Mapping.
        /// </summary>
        public static string LIS_File_Selection_and_Column_Mapping {
            get {
                return ResourceManager.GetString("LIS File Selection and Column Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        public static string Outputs {
            get {
                return ResourceManager.GetString("Outputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panels.
        /// </summary>
        public static string Panels {
            get {
                return ResourceManager.GetString("Panels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Simulation.
        /// </summary>
        public static string Run_Simulation {
            get {
                return ResourceManager.GetString("Run Simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Definition.
        /// </summary>
        public static string Scenario_Definition {
            get {
                return ResourceManager.GetString("Scenario Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Manager.
        /// </summary>
        public static string Scenario_Manager {
            get {
                return ResourceManager.GetString("Scenario Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Configuration.
        /// </summary>
        public static string Track_Configuration {
            get {
                return ResourceManager.GetString("Track Configuration", resourceCulture);
            }
        }
    }
}
